### PR TITLE
Add support for buffer instead of just files

### PR DESCRIPTION
**Pull request by kalsan**
This commit provides a new method `open_buffer` which allows to parse xlsx files from a buffer instead of a physical file. This is useful for example when gathering data from all xlsx files inside a zip without wanting to extract the zip first.

### CODE REVIEW

**Comment by kalsan** [comment]
Note: Tests are failing due to the changed internal interface.

**Comment by woahdae** [comment]
@kalsan I've re-implemented the internals in terms of a stream parser, and it seems like `SimpleXlsxReader.open` "just works" with IO, the tests pass at least. Would you be willing to give this a try: https://github.com/woahdae/simple_xlsx_reader/tree/2.0.0-pre

**Comment by woahdae** [comment]
I think this works in 2.0. Feel free to re-open if not.

**Comment by kalsan** [comment]
@woahdae sorry for the long wait. The interface producing this bug was replaced by a proper API and I was attempting to test your new version against the old version of the interface. I was unable to get the bug to show up in the lab situation and kept it in the backlog for later retry, which is why I didn't write back to you. I'm glad you took the courage to release it and I agree that this issue can remain closed.

**Pull request closed without merging**
