### PR TITLE
Support string or io input

### PR DESCRIPTION
**Pull request by til**
This builds upon #32 (@kalsan I hope you don't mind) and adds `SimpleXlsxReader.parse(string_or_io)` to support input other than a file path, with tests passing and tests added for `SimpleXlsxReader.open`.

### CODE REVIEW

**Comment by til** [comment]
Oh, it fails on Ruby 1.9, I didn't think of that. I might try to fix it later, not sure if it's easily doable.

**Comment by kalsan** [comment]
@til no problem, I'm happy to see that other people find it useful :-)

**Comment by til** [comment]
Rebased, build passing now.

**Comment by woahdae** [comment]
This looks great, thanks @kalsan and @til! @til your changes are very idiomatic to Ruby, much appreciated. Apologies for taking so long to get to looking at it.

**Comment by til** [comment]
@woahdae thank you for the kind words, and no worries.

**Comment by kalsan** [comment]
@til Awesome, thank you for enhancing this!
@woahdae thanks for merging and happy hacking!

**Pull request merged**
